Make our helper scripts more robus

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,29 +1,49 @@
 #!/bin/bash
-#
-# Build a new Python Docker image.
-#
-# Usage:
-#   ./build [--gpu] [--use-cache]
-#
-# Options:
-#   --gpu: Build an image with GPU support.
-#   --use-cache: Use layer cache when building a new image.
-# 
 set -e
-set -x
+
+usage() {
+cat << EOF
+Usage: $0 [OPTIONS]
+Build a new Python Docker image.
+
+Options:
+    -g, --gpu       Build an image with GPU support.
+    -c, --use-cache Use layer cache when building a new image.
+EOF
+}
 
 CACHE_FLAG="--no-cache"
-IMAGE_TAG="kaggle/python-build"
 DOCKERFILE="Dockerfile"
+IMAGE_TAG="kaggle/python-build"
 
-if [[ "$1" == "--gpu" ]]; then
-    IMAGE_TAG="kaggle/python-gpu-build"
-    DOCKERFILE="gpu.Dockerfile"
+while :; do
+    case "$1" in 
+        -h|--help)
+            usage
+            exit
+            ;;
+        -g|--gpu)
+            IMAGE_TAG="kaggle/python-gpu-build"
+            DOCKERFILE="gpu.Dockerfile"
+            ;;
+        -c|--use-cache)
+            CACHE_FLAG=""
+            ;;
+        -?*)
+            usage
+            printf 'ERROR: Unknown option: %s\n' "$1" >&2
+            exit
+            ;;
+        *)            
+            break
+    esac
+
     shift
-fi
+done
 
-if [[ "$1" ==  "--use-cache" ]]; then
-    CACHE_FLAG=""
-fi
+readonly CACHE_FLAG
+readonly DOCKERFILE
+readonly IMAGE_TAG
 
-docker build --rm $CACHE_FLAG -t $IMAGE_TAG -f $DOCKERFILE .
+set -x
+docker build --rm $CACHE_FLAG -t "$IMAGE_TAG" -f "$DOCKERFILE" .
diff --git a/push b/push
--- a/push
+++ b/push
@@ -1,35 +1,53 @@
 #!/bin/bash
-#
-# Push a newly-built image with the given label to gcr.io and DockerHub.
-#
-# Usage:
-#   ./push [--gpu] [LABEL]
-#
-# Description:
-#   LABEL: Docker image label. Defaults to "testing".
-#
-# Options:
-#   --gpu: Psuh the image with GPU support.
-# 
 set -e
-set -x
+
+usage() {
+cat << EOF
+Usage: $0 [OPTIONS] [LABEL]
+Push a newly-built image with the given LABEL to gcr.io and DockerHub.
+
+Options:
+    -g, --gpu   Push the image with GPU support.
+EOF
+}
 
 SOURCE_IMAGE="kaggle/python-build"
 TARGET_IMAGE="gcr.io/kaggle-images/python"
 
-if [[ "$1" == "--gpu" ]]; then
-    SOURCE_IMAGE="kaggle/python-gpu-build"
-    TARGET_IMAGE="gcr.io/kaggle-private-byod/python"
+while :; do
+    case "$1" in 
+        -h|--help)
+            usage
+            exit
+            ;;
+        -g|--gpu)
+            SOURCE_IMAGE="kaggle/python-gpu-build"
+            TARGET_IMAGE="gcr.io/kaggle-private-byod/python"
+            ;;
+        -?*)
+            usage
+            printf 'ERROR: Unknown option: %s\n' "$1" >&2
+            exit
+            ;;
+        *)            
+            break
+    esac
+
     shift
-fi
+done
 
 LABEL=${1:-testing}
 
-docker tag $SOURCE_IMAGE:latest $TARGET_IMAGE:$LABEL
-gcloud docker -- push $TARGET_IMAGE:$LABEL
+readonly SOURCE_IMAGE
+readonly TARGET_IMAGE
+readonly LABEL
+
+set -x
+docker tag "${SOURCE_IMAGE}:latest" "${TARGET_IMAGE}:${LABEL}"
+gcloud docker -- push "${TARGET_IMAGE}:${LABEL}"
 
 # Only CPU images are made public at this time.
 if [[ "$LABEL" == "latest" && SOURCE_IMAGE = "kaggle/python-build" ]]; then
-  docker tag $SOURCE_IMAGE:latest kaggle/python:$LABEL
-  docker push kaggle/python:$LABEL
+  docker tag "${SOURCE_IMAGE}:latest" "kaggle/python:${LABEL}"
+  docker push "kaggle/python:${LABEL}"
 fi
diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
-# Run tests for a newly-built Python Docker image.
-# By default, it runs the tests for the CPU image.
+# 
+# 
 #
 # Usage:
 #   ./test [--gpu]
@@ -9,19 +9,48 @@
 # Options:
 #   --gpu: Run tests for the GPU image
 # 
-
 set -e
-set -x
+
+usage() {
+cat << EOF
+Usage: $0 [OPTIONS]
+Run tests for a newly-built Python Docker image.
+By default, it runs the tests for the CPU image.
+
+Options:
+    -g, --gpu   Run tests for the GPU image.
+EOF
+}
 
 IMAGE_TAG="kaggle/python-build"
 ADDITONAL_OPTS=""
 
-if [[ "$1" == "--gpu" ]]; then
-    IMAGE_TAG="kaggle/python-gpu-build"
-    ADDITONAL_OPTS="-v /tmp/empty_dir:/usr/local/cuda/lib64/stubs:ro"
-    shift
-fi
+while :; do
+    case "$1" in 
+        -h|--help)
+            usage
+            exit
+            ;;
+        -g|--gpu)
+            IMAGE_TAG="kaggle/python-gpu-build"
+            ADDITONAL_OPTS="-v /tmp/empty_dir:/usr/local/cuda/lib64/stubs:ro"
+            ;;
+        -?*)
+            usage
+            printf 'ERROR: Unknown option: %s\n' "$1" >&2
+            exit
+            ;;
+        *)            
+            break
+    esac
 
+    shift
+done
+
+readonly IMAGE_TAG
+readonly ADDITONAL_OPTS
+
+set -x
 rm -rf /tmp/python-build
 docker rm jupyter_test || true
 mkdir -p /tmp/python-build/tmp
@@ -39,5 +68,5 @@ docker run --rm -t --read-only --net=none \
     -v /tmp/python-build/tmp:/tmp -v /tmp/python-build/devshm:/dev/shm \
     -w=/working \
     $ADDITONAL_OPTS \
-    $IMAGE_TAG \
+    "$IMAGE_TAG" \
     /bin/bash -c 'python -m unittest discover -s /input/tests'
