Add TODOs and improve build/push script

diff --git a/tensorflow-whl/build b/tensorflow-whl/build
--- a/tensorflow-whl/build
+++ b/tensorflow-whl/build
@@ -1,11 +1,42 @@
 #!/bin/bash
 set -e
-set -x
 
-# Default behavior is to do everything from scratch.
-# The --use-cache option is useful if you're iterating on a broken build.
-if [[ "$1" ==  "--use-cache" ]]; then
-    docker build --rm -t kaggle/python-tensorflow-whl .
-else
-    docker build --pull --rm --no-cache -t kaggle/python-tensorflow-whl .
-fi
+usage() {
+cat << EOF
+Usage: $0 [OPTIONS]
+Build new Tensorflow wheels for use in the Kaggle Docker Python base images.
+
+Options:
+    -c, --use-cache Use layer cache when building a new image.
+EOF
+}
+
+CACHE_FLAG="--no-cache"
+IMAGE_TAG="kaggle/python-build"
+
+while :; do
+    case "$1" in 
+        -h|--help)
+            usage
+            exit
+            ;;
+        -c|--use-cache)
+            CACHE_FLAG=""
+            ;;
+        -?*)
+            usage
+            printf 'ERROR: Unknown option: %s\n' "$1" >&2
+            exit
+            ;;
+        *)            
+            break
+    esac
+
+    shift
+done
+
+readonly CACHE_FLAG
+readonly IMAGE_TAG
+
+set -x
+docker build --rm --pull $CACHE_FLAG -t "$IMAGE_TAG" .
diff --git a/tensorflow-whl/push b/tensorflow-whl/push
--- a/tensorflow-whl/push
+++ b/tensorflow-whl/push
@@ -1,18 +1,36 @@
 #!/bin/bash
-#
-# Push a newly-built image with the given label to gcr.io and DockerHub.
-#
-# Usage:
-#   ./push LABEL
-#
-# Description:
-#   LABEL: Image label. See CHANGELOG.md
-#
 set -e
+
+usage() {
+cat << EOF
+Usage: $0 [LABEL]
+Push a newly-built image with the given LABEL to gcr.io and DockerHub.
+See CHANGELOG.md file for LABEL naming convention.
+EOF
+}
+
 set -x
 
 SOURCE_IMAGE="kaggle/python-tensorflow-whl"
 TARGET_IMAGE="gcr.io/kaggle-images/python-tensorflow-whl"
+
+while :; do
+    case "$1" in 
+        -h|--help)
+            usage
+            exit
+            ;;
+        -?*)
+            usage
+            printf 'ERROR: Unknown option: %s\n' "$1" >&2
+            exit
+            ;;
+        *)            
+            break
+    esac
+
+    shift
+done
 
 LABEL=$1
 
@@ -21,5 +39,10 @@ if [[ -z "$LABEL" ]]; then
     exit 1
 fi
 
-docker tag $SOURCE_IMAGE:latest $TARGET_IMAGE:$LABEL
-gcloud docker -- push $TARGET_IMAGE:$LABEL
+readonly SOURCE_IMAGE
+readonly TARGET_IMAGE
+readonly LABEL
+
+set -x
+docker tag "$SOURCE_IMAGE:latest" "$TARGET_IMAGE:$LABEL"
+gcloud docker -- push "$TARGET_IMAGE:$LABEL"
